version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Mapeia a porta 8000 do host para a porta 80 do contêiner
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: amigo_secreto
      DB_USERNAME: root
      DB_PASSWORD: admin123

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: amigo_secreto
    ports:
      - "3306:3306" # Mapeia a porta 3306 do host para a porta 3306 do contêiner
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
